# Generated by Django 5.1.3 on 2024-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
